[package]
name = "owldict"
version = "0.1.0"
authors = ["Spyros Roum <spyrosr1@gmail.com>"]
edition = "2018"


[dependencies]
ureq = { version = "1", features = ["json"] }
serde = "1"
clap = "2"
dotenv = "0.15"
